StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65E911FDEFB5E5C4}" {
   Id "AR-RKN_S02TT-Course_Beige1_Desc"
   Target_en_us "1) Move through the canyon to the tunnel entrance. Engage targets along the way."\
   ""\
   "2) Clear out the tunnel."\
   ""\
   "3) Take the tunnel exit to left at the fork."\
   ""\
   "4) Ascend the hill. Engage targets to the front. Then turn right into the ruins."\
   ""\
   "5) Move through the ruins and engage far targets at the shooting position."
   Modified 1709788265
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144B562167E}" {
   Id "AR-RKN_S02TT-Course_Beige1_Name"
   Target_en_us "Tunnel Rat"
   Modified 1709902137
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DF3610E1CB3A07}" {
   Id "AR-RKN_S02TT-Course_Black1_Desc"
   Target_en_us "1) Engage the targets in front, down the path."\
   ""\
   "2) Take a left and enter the dry channel. Move along it while engaging targets."\
   ""\
   "3) At the end, take a left up between the rocks and then down to the water front street. Engage the targets on the beach and in the water."\
   ""\
   "4) Move through the backalley while engagin targets to the left."\
   ""\
   "5) At the road, take a left to the sanbag positions. Engage targets at the refueling station. Turn around and engage targets at the next sandbags."\
   ""\
   "6) Move into the church and engage targets from the lower level."\
   ""\
   "7) Move up the stairs to the belltower. Engage targets out the doors to your right after ascending the ladder. Then turn 180 and do the same on the other side."\
   ""\
   "8) Turn left out the last tower doors onto the roof. Sprint to the finish line on the other end of the roof."
   Modified 1709644576
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144AA7FF713}" {
   Id "AR-RKN_S02TT-Course_Black1_Name"
   Target_en_us "Naval Nuisance"
   Modified 1709902160
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DF3610E3E335DA}" {
   Id "AR-RKN_S02TT-Course_Black2_Desc"
   Target_en_us "Oh god they're multiplying!"
   Modified 1709130439
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144A3640D7B}" {
   Id "AR-RKN_S02TT-Course_Black2_Name"
   Target_en_us "Clownhouse"
   Modified 1709902171
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65E70C77D6A20B7A}" {
   Id "AR-RKN_S02TT-Course_Black3_Desc"
   Target_en_us "1) Engage targets while leaning from sandbag cover with pistol."\
   ""\
   "2) Shoot the targets in prone position under the tin wall."\
   ""\
   "3) Move to the left, and engage targets again on the first range with pistol while standing."\
   ""\
   "4) Move to next position down the street along the sidewalk. Engage targets in the windows of the opposite building from crouch position. You may need to use the full range of the variable stance system to hit all targets while crouched."\
   ""\
   "5) Move further down the street to next position and repeat previous step, from standing position this time."\
   ""\
   "6) Move across the street and shoot the targets within the courtyard."\
   ""\
   "7) Move back out of the courtyard, take a right towards the sandbag shooting position, and engage targets at long range with precision rifle."\
   ""\
   "8) Take a left and shoot targets through the first and then second hole in the sandbag wall."\
   ""\
   "9) Sprint to the finish to your left."
   Modified 1709644173
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144DBAA7DE0}" {
   Id "AR-RKN_S02TT-Course_Black3_Name"
   Target_en_us "Phillip's Street"
   Modified 1709902186
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA66671FF08947}" {
   Id "AR-RKN_S02TT-Course_Blue1_Desc"
   Target_en_us "A course is split into sections. Completing sections usually means shooting all targets from a specific position, before moving on to the next section at a new position. These positions can sometimes have requirements, such as stance and weapon type. Leaving the shooting position before completing the section may result in failure of the course."\
   ""\
   "At each section you will notice a number in your upper left corner, which will count down each time you hit a target. This is the counter for remaining required objectives of the current section."\
   ""\
   "For this course you must shoot the targets at each of the three positions. They each have stance and weapon requirements, which must be met before the targets are activated."
   Modified 1708850080
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144D2D2072F}" {
   Id "AR-RKN_S02TT-Course_Blue1_Name"
   Target_en_us "Range Sequence"
   Modified 1709902202
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA661C1099D7A7}" {
   Id "AR-RKN_S02TT-Course_Blue2_Desc"
   Target_en_us "Train your accuracy while moving and inhibited by obstacles."
   Modified 1708839249
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144C9651749}" {
   Id "AR-RKN_S02TT-Course_Blue2_Name"
   Target_en_us "Killhouse"
   Modified 1709902214
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EA5524AC1BAB12}" {
   Id "AR-RKN_S02TT-Course_Blue3_Desc"
   Target_en_us "1) Clear all obstacles to the left. "\
   ""\
   "2) Turn 180 right and complete the center obstacles."\
   ""\
   "3) Sprint to the finish line near the flagpole."
   Modified 1709891305
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144C45209D8}" {
   Id "AR-RKN_S02TT-Course_Blue3_Name"
   Target_en_us "Obstacle Course"
   Modified 1709902221
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EA555A939F3EE2}" {
   Id "AR-RKN_S02TT-Course_Brown1_Desc"
   Target_en_us "For each section, find the window with the active target. After hitting it a sequence of timed targets will appear."
   Modified 1709882503
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144FBE175EC}" {
   Id "AR-RKN_S02TT-Course_Brown1_Name"
   Target_en_us "Whack-an-Invader"
   Modified 1709902243
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA6624E48E7FAA}" {
   Id "AR-RKN_S02TT-Course_Green1_Desc"
   Target_en_us "1) Engage the targets to your left."\
   ""\
   "2) Exit the road and follow the path marked by painted poles."\
   ""\
   "3) Move to the first shooting position and engage targets at long range."\
   ""\
   "4) Stand and follow the path."\
   ""\
   "5) Move to the second shooting position and engage targets at long range."
   Modified 1708838367
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144F3112D91}" {
   Id "AR-RKN_S02TT-Course_Green1_Name"
   Target_en_us "Extended Range"
   Modified 1709902257
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA6612B4DDE26E}" {
   Id "AR-RKN_S02TT-Course_Intro_Desc"
   Target_en_us "There are three different targets. Standard, popper, and clay disc."\
   ""\
   "Popper targets are the small white metal ones. Standard targets are the large wooden ones with image of a man on the front. Shooting these two types are usually a requirement to proceed."\
   ""\
   "Clay targets are the red discs on wooden poles. They are optional targets that give bonus time."\
   ""\
   "Popper and standard targets can also give bonus if you hit the center of each."\
   ""\
   "Civilian targets are the purple static ones. If hit you will be given a penalty."\
   ""\
   "Targets can only be shot while activated. Popper and standard targets can fold, and are activated once they are upright."\
   ""\
   "Targets will generally activate once their assigned course section is activated. But their activation can also be configured to be delayed by some time. Additionally, they may have some prerequiside objective. Usually a shooting position, but can also be another target."\
   ""\
   "Targets can sometimes be placed on rails, which allow them to move."
   Modified 1708851417
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144EA8D0C19}" {
   Id "AR-RKN_S02TT-Course_Intro_Name"
   Target_en_us "Introduction Course"
   Modified 1709902273
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65E0BA89D0709DBF}" {
   Id "AR-RKN_S02TT-Course_Lime1_Desc"
   Target_en_us "1) Shoot all targets on or at the base of the walls."\
   ""\
   "2) Enter through the opened gate and engage those targets at the entrance."\
   ""\
   "3) Turn left and engage targets near the camping area."\
   ""\
   "4) Turn right and up the center ruins, and clear it."\
   ""\
   "5) Cross the bridge, clear the area, and open the cage."
   Modified 1709231761
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE1441C149833}" {
   Id "AR-RKN_S02TT-Course_Lime1_Name"
   Target_en_us "Rescue The Princess"
   Modified 1709902295
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA660CA6BF930A}" {
   Id "AR-RKN_S02TT-Course_Orange1_Desc"
   Target_en_us "1) Engage the targets to the left. Then proceed through the forest to the pond, by follwing the red barriers."\
   ""\
   "2) Move to the edge of the pond and engage the targets."\
   ""\
   "3) Move clockwise around the pond and engage targets from the first sandbags."\
   ""\
   "4) Continue to the second set of sandbags and engage the targets by the bee hives."\
   ""\
   "5) Jump over the fence and drive the vehicle along the designated path to the beach."\
   ""\
   "6) Enter the bunker and engage the targets on the other side of the bay."
   Modified 1708838371
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE144142619F7}" {
   Id "AR-RKN_S02TT-Course_Orange1_Name"
   Target_en_us "Fisherman"
   Modified 1709902305
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA6624E3BFBA07}" {
   Id "AR-RKN_S02TT-Course_Red1_Desc"
   Target_en_us "1) Enter the yard and engage targets."\
   ""\
   "2) Enter through the backdoor of the building and clear it of targets."\
   ""\
   "3) Exit through the front door to the finish line."
   Modified 1708838374
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE1440FA6F2ED}" {
   Id "AR-RKN_S02TT-Course_Red1_Name"
   Target_en_us "Home Invasion"
   Modified 1709902319
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA66241CF3131B}" {
   Id "AR-RKN_S02TT-Course_Red2_Desc"
   Target_en_us "1) Enter the building and move through the corridor to the far-end exit. Engage targets to your left and right along the way."\
   ""\
   "2) Clear targets in the backyard and exit through the fence in the back."\
   ""\
   "3) Turn left and engage targets at the first range."\
   ""\
   "4) Turn right and head into the field where there towards the second range."\
   ""\
   "5) Engage the targets at the second range from a crouched position."\
   ""\
   "6) Turn right and clear the yard of the next building complex."\
   ""\
   "7) Move to the far left side of the yard, climb the stairs, and engage the targets at the third range with your rifle."
   Modified 1708838377
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE1440AB7B897}" {
   Id "AR-RKN_S02TT-Course_Red2_Name"
   Target_en_us "Crop Harvesting"
   Modified 1709902328
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65D8CECE4034DD39}" {
   Id "AR-RKN_S02TT-Course_Red3_Desc"
   Target_en_us "1) Move to the vehicle while engaging the targets to your right."\
   ""\
   "2) Enter the vehicle and follow the route to the military base. Navigate through the base until you get to the target range, at which point to exit the vehicle."\
   ""\
   "3) Engage target at the range."\
   ""\
   "4) Enter the multi-story building and make your way to the roof."\
   ""\
   "5) Engage targets along the mountain at long range."\
   ""\
   "6) Descend the ladder to the finish line."
   Modified 1708838381
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE14406DEF5E4}" {
   Id "AR-RKN_S02TT-Course_Red3_Name"
   Target_en_us "Drive-in"
   Modified 1709902339
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65DA662709656AAA}" {
   Id "AR-RKN_S02TT-Course_Yellow1_Desc"
   Target_en_us "1) Clear the building."\
   ""\
   "2) Exit to the courtyard through the backdoor, enter the marked position and engage the targets as they activate."\
   ""\
   "3) Enter and move through the garage and exit thorugh the south-east door."\
   ""\
   "4) Move along the wall, cross the road, and engage the targets in the area."\
   ""\
   "5) Move to the finish line down the dirt path."
   Modified 1708838384
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65EAE1443ED491BB}" {
   Id "AR-RKN_S02TT-Course_Yellow1_Name"
   Target_en_us "Funhouse"
   Modified 1709902352
   Author "Rune"
   LastChanged "Rune"
  }
 }
}