StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65D8CECE4034DD39}" {
   Id "AR-RKN_S01TT-Course_Red1_Desc"
   Target_en_us "1) Move to the vehicle while engaging the targets to your right."\
   ""\
   "2) Enter the vehicle and follow the route to the military base. Navigate through the base until you get to the target range, at which point to exit the vehicle."\
   ""\
   "3) Engage target at the range."\
   ""\
   "4) Enter the multi-story building and make your way to the roof."\
   ""\
   "5) Engage targets along the mountain at long range."\
   ""\
   "6) Descend the ladder to the finish line."
   Modified 1708727748
   Author "Rune"
   LastChanged "Rune"
  }
 }
}