SCR_MapConfig {
 m_iMapMode FULLSCREEN
 m_LayersConfig SCR_MapLayersBase "{58C8DDC97E580BED}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{58C89E75E1BB275D}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aModules {
  SCR_MapCursorModule "{58ECED62053B9098}" : "{5E40C9235FDA4430}Configs/Map/Prefabs/MapCursorModuleDef.conf" {
   m_bEnableCrosshairCoords 1
   m_aCursorStatesConfig {
    SCR_CursorVisualState "{58EC8D7AB607CC2D}" {
    }
   }
  }
 }
 m_aUIComponents {
  SCR_MapRadialUI "{65D85ECC1F1879CE}" {
   m_RadialController SCR_RadialMenuController "{65D85ECC1F1879D5}" {
    m_RMControls SCR_RadialMenuControllerInputs "{65D85ECC1F185CFC}" {
     m_bCloseOnReleaseOpen 0
     m_bPerformOnClose 0
     m_bCloseOnPerform 1
    }
    m_Data SCR_SelectionMenuData "{65D85ECC1F185CFF}" {
    }
   }
   m_RadialMenu SCR_RadialMenu "{5D9A83188B57DA4B}" : "{D9448EF097CB0ACB}Configs/HUD/RadialMenu/GlobalRadialMenu.conf" {
   }
  }
  SCR_MapUIElementContainer "{65D85ECC1F185CF1}" {
  }
  SCR_MapLightUI "{65D85ECC1F185CF2}" {
  }
  SCR_MapToolInteractionUI "{65D85ECC1F188F52}" {
  }
  SCR_MapWatchUI "{65D85ECC1F188F53}" {
   m_aSizesArray {
    ToolSize "{65D85ECC1F1898DE}" {
     m_iSizeX 150
     m_iSizeY 187
    }
    ToolSize "{65D85ECC1F1898D8}" {
     m_iSizeX 250
     m_iSizeY 312
    }
   }
  }
  SCR_MapDebugUI "{65D85ECC1F1898DB}" {
   m_fUnitIconRotation -90
  }
  SCR_MapRulerUI "{5EB0852B02C40995}" : "{7884D3EDB4762263}Configs/Map/Prefabs/MapRulerUIDef.conf" {
  }
  SCR_MapToolMenuUI "{65D85ECC1F1898DA}" {
  }
  SCR_MapTaskListUI "{65D85ECC1F1898E5}" {
  }
  SCR_MapDrawingUI "{65D85ECC1F1898E1}" {
  }
  SCR_MapMarkersUI "{65D85ECC1F1898E0}" {
  }
  SCR_MapCompassUI "{5E88A0BAA9983F29}" : "{D1282B3EA205074A}Configs/Map/Prefabs/MapCompassUIDef.conf" {
  }
  SCR_MapJournalUI "{65D85ECC1F1898E3}" {
   m_sMapTaskListFrame "MapTaskList"
  }
 }
 m_bEnableLegendScale 1
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{58C8DDC9087BF565}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{58C89E6280B692A8}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
 }
}