RKN_TimeTrialCourseConfig {
 m_sId "beige1"
 m_sName "#AR-RKN_S02TT-Course_Beige1_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Beige1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65E911FE28C6EBC1}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65E911FE28C6EBC7}" {
   m_sPrefab "{B31929F65F0D0279}Prefabs/Weapons/Rifles/M14/Rifle_M21.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65E911FE28C6EBC9}" {
   m_sPrefab "{C319540BC96AE9BB}Prefabs/Weapons/Magazines/Magazine_762x51_M14_20rnd_M61_AP.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 150
 m_fSilverSeconds 105
 m_fGoldSeconds 72
}