RKN_TimeTrialCourseConfig {
 m_sId "black2"
 m_sName "#AR-RKN_S02TT-Course_Black2_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Black2_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DE9B1AF285599F}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65DE9B1AF28559A4}" {
   m_sPrefab "{D2B48DEBEF38D7D7}Prefabs/Weapons/MachineGuns/M249/MG_M249.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DE9B1AF28559A9}" {
   m_sPrefab "{4FCBBDF274FD2157}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65DE9B1A15C4B198}" {
   m_sPrefab "{E8F00BF730225B00}Prefabs/Weapons/Grenades/Grenade_M67.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 100
 m_fSilverSeconds 50
 m_fGoldSeconds 30
}