RKN_TimeTrialCourseConfig {
 m_sId "black1"
 m_sName "Naval Nuisance"
 m_sDescription "#AR-RKN_S02TT-Course_Black1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DE63719A5023DC}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65DE63719A5023E5}" {
   m_sPrefab "{FA5C25BF66A53DCF}Prefabs/Weapons/Rifles/AK74/Rifle_AK74.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DE63719A5023EE}" {
   m_sPrefab "{BBB50A815A2F916B}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Ball.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 300
 m_fSilverSeconds 230
 m_fGoldSeconds 190
}