RKN_TimeTrialCourseConfig {
 m_sId "black3"
 m_sName "Phillip's Street"
 m_sDescription "#AR-RKN_S02TT-Course_Black3_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65E0F61C89056B5A}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65E0F61C89056B63}" {
   m_sPrefab "{8B853CDD11BA916E}Prefabs/Weapons/Magazines/Magazine_9x18_PM_8rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65E0F61C89056B64}" {
   m_sPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65E0F61C89056B69}" {
   m_sPrefab "{9C948630078D154D}Prefabs/Weapons/Rifles/VZ58/Rifle_VZ58P.et"
  }
  RKN_TimeTrialLoadoutItem "{65E0F61C89056B6B}" {
   m_sPrefab "{BBB50A815A2F916B}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65E0F615B9218CF5}" {
   m_sPrefab "{81EB948E6414BD6F}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et"
  }
  RKN_TimeTrialLoadoutItem "{65E0F615AF976BDE}" {
   m_sPrefab "{C319540BC96AE9BB}Prefabs/Weapons/Magazines/Magazine_762x51_M14_20rnd_M61_AP.et"
  }
 }
 m_fBronzeSeconds 130
 m_fSilverSeconds 100
 m_fGoldSeconds 80
}