RKN_TimeTrialCourseConfig {
 m_sId "blue2"
 m_sName "Killhouse"
 m_sDescription "#AR-RKN_S02TT-Course_Blue2_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DA6668BC265A55}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DA6668BC265A59}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 2
  }
 }
 m_fBronzeSeconds 24
 m_fSilverSeconds 13
 m_fGoldSeconds 9
}