RKN_TimeTrialCourseConfig {
 m_sId "blue3"
 m_sName "Obstacle Course"
 m_sDescription "#AR-RKN_S02TT-Course_Blue3_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65EA55249610DE2F}" {
   m_sPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65EA55249610DE35}" {
   m_sPrefab "{8B853CDD11BA916E}Prefabs/Weapons/Magazines/Magazine_9x18_PM_8rnd_Ball.et"
   m_iCount 2
  }
 }
 m_fBronzeSeconds 90
 m_fSilverSeconds 71
 m_fGoldSeconds 58
}