RKN_TimeTrialCourseConfig {
 m_sId "blue1"
 m_sName "Range Sequence"
 m_sDescription "#AR-RKN_S02TT-Course_Blue1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DA66689A87736D}" {
   m_sPrefab "{F396524995F06BFA}Prefabs/Characters/Vests/Vest_SRU21P/Vest_SRU21P.et"
  }
  RKN_TimeTrialLoadoutItem "{65DA6613C414CF79}" {
   m_sPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DA6613C414CF7A}" {
   m_sPrefab "{8B853CDD11BA916E}Prefabs/Weapons/Magazines/Magazine_9x18_PM_8rnd_Ball.et"
   m_iCount 2
  }
  RKN_TimeTrialLoadoutItem "{65DA666B46207AA6}" {
   m_sPrefab "{EB404DC9E1BCB750}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N_1P29.et"
  }
  RKN_TimeTrialLoadoutItem "{65DA666B71C2F005}" {
   m_sPrefab "{BC74DAC891D48540}Prefabs/Weapons/Magazines/Magazine_545x39_RPK_45rnd_Ball.et"
   m_iCount 2
  }
 }
 m_fBronzeSeconds 50
 m_fSilverSeconds 30
 m_fGoldSeconds 20
}