RKN_TimeTrialCourseConfig {
 m_sId "green1"
 m_sName "Extended Range"
 m_sDescription "#AR-RKN_S02TT-Course_Green1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65D8CEED0A28E325}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65D8CEED0A28E32A}" {
   m_sPrefab "{48720FC416263FC1}Prefabs/Weapons/Magazines/Vz58/Magazine_762x39_Vz58_30rnd_Ball.et"
   m_iCount 2
  }
  RKN_TimeTrialLoadoutItem "{65D8CEED0A28E32E}" {
   m_sPrefab "{443CEFF17E040B11}Prefabs/Weapons/Rifles/VZ58/Rifle_VZ58V.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65D8CEED0A28E330}" {
   m_sPrefab "{6415B7923DE28C1B}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_PSO.et"
  }
  RKN_TimeTrialLoadoutItem "{65D8CEED0A28E332}" {
   m_sPrefab "{9CCB46C6EE632C1A}Prefabs/Weapons/Magazines/Magazine_762x54_SVD_10rnd_Sniper.et"
   m_iCount 4
  }
 }
 m_fBronzeSeconds 180
 m_fSilverSeconds 145
 m_fGoldSeconds 130
}