RKN_TimeTrialCourseConfig {
 m_sId "intro"
 m_sName "Introduction Course"
 m_sDescription "#AR-RKN_S02TT-Course_Intro_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DA6613C414CF79}" {
   m_sPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DA6613C414CF7A}" {
   m_sPrefab "{8B853CDD11BA916E}Prefabs/Weapons/Magazines/Magazine_9x18_PM_8rnd_Ball.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 10
 m_fSilverSeconds 6
 m_fGoldSeconds 3
}