RKN_TimeTrialCourseConfig {
 m_sId "lime1"
 m_sName "#AR-RKN_S02TT-Course_Lime1_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Lime1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65E055DE6B5DC9FF}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65E055DE6B5DC98D}" {
   m_sPrefab "{BFF3186D2A9CEFB7}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_AP2k.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65E055DE6B5DC98F}" {
   m_sPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
   m_iCount 2
  }
 }
 m_fBronzeSeconds 200
 m_fSilverSeconds 150
 m_fGoldSeconds 110
}