RKN_TimeTrialCourseConfig {
 m_sId "orange1"
 m_sName "#AR-RKN_S02TT-Course_Orange1_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Orange1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DA660A0E669FE6}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65DA660A0E669FEE}" {
   m_sPrefab "{E57DBDA5C50F07FF}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_4x20.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65DA660A0E669FF9}" {
   m_sPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
   m_iCount 2
  }
 }
 m_fBronzeSeconds 180
 m_fSilverSeconds 145
 m_fGoldSeconds 130
}