SCR_VoiceoverData {
 m_aLines {
  SCR_VoiceoverLineStandalone "{65D0F004F4689462}" {
   m_sSoundEventName "SOUND_RO_START"
   m_sName "START"
  }
  SCR_VoiceoverLineStandalone "{65D0F0041CB74346}" {
   m_sSoundEventName "SOUND_RO_PENALTY"
   m_sName "PENALTY"
  }
  SCR_VoiceoverLineStandalone "{65D0F0040C108444}" {
   m_sSoundEventName "SOUND_RO_BONUS"
   m_sName "BONUS"
  }
  SCR_VoiceoverLineStandalone "{65D0F0040AFF97A9}" {
   m_sSoundEventName "SOUND_RO_HIT"
   m_sName "HIT"
  }
  SCR_VoiceoverLineStandalone "{65D0F00402FE7F25}" {
   m_sSoundEventName "SOUND_RO_RIFLE"
   m_sName "RIFLE"
  }
  SCR_VoiceoverLineStandalone "{65D0F00432C97BB8}" {
   m_sSoundEventName "SOUND_RO_PISTOL"
   m_sName "PISTOL"
  }
  SCR_VoiceoverLineStandalone "{65D0F0042483B9E2}" {
   m_sSoundEventName "SOUND_RO_GRENADE"
   m_sName "GRENADE"
  }
  SCR_VoiceoverLineStandalone "{65D0F0045EED852D}" {
   m_sSoundEventName "SOUND_RO_LEAN"
   m_sName "LEAN"
  }
  SCR_VoiceoverLineStandalone "{65D0F00454B963A1}" {
   m_sSoundEventName "SOUND_RO_STAND"
   m_sName "STAND"
  }
  SCR_VoiceoverLineStandalone "{65D0F0044C975536}" {
   m_sSoundEventName "SOUND_RO_CROUCH"
   m_sName "CROUCH"
  }
  SCR_VoiceoverLineStandalone "{65D0F0044791C38D}" {
   m_sSoundEventName "SOUND_RO_PRONE"
   m_sName "PRONE"
  }
  SCR_VoiceoverLineStandalone "{65D0F00442577244}" {
   m_sSoundEventName "SOUND_RO_SECTION"
   m_sName "SECTION"
  }
  SCR_VoiceoverLineStandalone "{65D0F0046157EFDD}" {
   m_sSoundEventName "SOUND_RO_FINISH_BRONZE"
   m_sName "FINISH_BRONZE"
  }
  SCR_VoiceoverLineStandalone "{65D0F00798E5FA9A}" {
   m_sSoundEventName "SOUND_RO_FINISH_SILVER"
   m_sName "FINISH_SILVER"
  }
  SCR_VoiceoverLineStandalone "{65D0F00792B9A015}" {
   m_sSoundEventName "SOUND_RO_FINISH_GOLD"
   m_sName "FINISH_GOLD"
  }
  SCR_VoiceoverLineStandalone "{65D0F007885CBE18}" {
   m_sSoundEventName "SOUND_RO_FINISH_PB"
   m_sName "FINISH_PB"
  }
  SCR_VoiceoverLineStandalone "{65D0F007834F9FC4}" {
   m_sSoundEventName "SOUND_RO_FINISH_NONE"
   m_sName "FINISH_NONE"
  }
 }
 m_aSequences {
  SCR_VoiceoverSequence "{65D0F007B53A0585}" {
   m_sName "SPAWN"
   m_aLines {
    SCR_VoiceoverLine "{65D0F007B09CDC5B}" {
     m_sSoundEventName "SOUND_RO_SPAWN_1"
    }
    SCR_VoiceoverLine "{65D0F007A4476A5A}" {
     m_sSoundEventName "SOUND_RO_SPAWN_2"
    }
    SCR_VoiceoverLine "{65D0F007A13FAF62}" {
     m_sSoundEventName "SOUND_RO_SPAWN_3"
    }
   }
  }
 }
}