RKN_TimeTrialCourseConfig {
 m_sId "red1"
 m_sName "#AR-RKN_S02TT-Course_Red1_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Red1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65CE7B4B3B712BD8}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65CE7B4B3B712BE1}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
   m_bEquip 1
  }
 }
 m_fBronzeSeconds 40
 m_fSilverSeconds 25
 m_fGoldSeconds 20
}