RKN_TimeTrialCourseConfig {
 m_sName "Red One"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65CE7B4B3B712BD8}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65CE7B4B3B712BE1}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
  }
 }
 m_iBronze 10000
 m_iSilver 8000
 m_iGold 5000
}