RKN_TimeTrialCourseConfig {
 m_sId "red2"
 m_sName "#AR-RKN_S02TT-Course_Red2_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Red2_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65D6AAAE5541631D}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65D6AAAE2DFC3D40}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65D6AAAE2DFC3D49}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65D6AAAE2EF9E5A5}" {
   m_sPrefab "{3E413771E1834D2F}Prefabs/Weapons/Rifles/M16/Rifle_M16A2.et"
  }
  RKN_TimeTrialLoadoutItem "{65D6AAAE4E5DF9C4}" {
   m_sPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 100
 m_fSilverSeconds 80
 m_fGoldSeconds 60
}