RKN_TimeTrialCourseConfig {
 m_sId "red3"
 m_sName "#AR-RKN_S02TT-Course_Red3_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Red3_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65D6F2F07EC99318}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65D6F2F07EC99323}" {
   m_sPrefab "{BBB50A815A2F916B}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Ball.et"
   m_iCount 3
  }
  RKN_TimeTrialLoadoutItem "{65D6F2F07EC99324}" {
   m_sPrefab "{BFEA719491610A45}Prefabs/Weapons/Rifles/AKS74U/Rifle_AKS74U.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65D6F2F07EC99329}" {
   m_sPrefab "{81EB948E6414BD6F}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et"
  }
  RKN_TimeTrialLoadoutItem "{65D6F2F07EC9932A}" {
   m_sPrefab "{C319540BC96AE9BB}Prefabs/Weapons/Magazines/Magazine_762x51_M14_20rnd_M61_AP.et"
   m_iCount 3
  }
 }
 m_fBronzeSeconds 180
 m_fSilverSeconds 145
 m_fGoldSeconds 130
}