RKN_TimeTrialCourseConfig {
 m_sId "yellow1"
 m_sName "#AR-RKN_S02TT-Course_Yellow1_Name"
 m_sDescription "#AR-RKN_S02TT-Course_Yellow1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65DA662045BC9478}" {
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
  }
  RKN_TimeTrialLoadoutItem "{65DA66207C4977D4}" {
   m_sPrefab "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65D91E0BD0243B7D}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
  }
  RKN_TimeTrialLoadoutItem "{65D91E0BD0243B00}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 5
  }
  RKN_TimeTrialLoadoutItem "{65DA66207483F142}" {
   m_sPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
  }
 }
 m_fBronzeSeconds 180
 m_fSilverSeconds 135
 m_fGoldSeconds 110
}