RKN_TimeTrialCourseConfig {
 m_sId "yellow1"
 m_sName "Yellow One"
 m_sDescription "#AR-RKN_S01TT-Course_Yellow1_Desc"
 m_aCompetitiveLoadout {
  RKN_TimeTrialLoadoutItem "{65D91E0BD0243B7D}" {
   m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
   m_bEquip 1
  }
  RKN_TimeTrialLoadoutItem "{65D91E0BD0243B00}" {
   m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iCount 5
  }
 }
 m_fBronzeSeconds 180
 m_fSilverSeconds 145
 m_fGoldSeconds 130
}