SCR_JournalSetupConfig {
 m_iJournalEntryToShowOnStart 1
 m_aJournals {
  SCR_JournalConfig "{6636E0170F27C629}" {
   m_aEntries {
    SCR_JournalEntry "{6636E017094D25FD}" {
     m_iEntryID 1
     m_eJournalEntryType Custom
     m_sCustomEntryName "#AR-RKN_S02TT-Journal_Intro_Title"
     m_sEntryText "#AR-RKN_S02TT-Journal_Intro_Text"
    }
   }
  }
 }
}