SCR_MissionHeaderCombatOps {
 World "{92624E92F6AEA8D4}worlds/rknSP02TT.ent"
 m_sName "RKN Time Trials - Everon"
 m_sAuthor "Runekn"
 m_sDetails "<Insert scenario details>"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "RKN Time Trials"
 m_bIsSavingEnabled 1
 m_sSaveFileName "RKN_TImeTrials_Eden"
}