SCR_MissionHeaderCombatOps {
 World "{92624E92F6AEA8D4}worlds/rknSP02TT.ent"
 m_sName "Everon Time Trials"
 m_sAuthor "Runekn"
 m_sDetails "<Insert scenario details>"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_eEditableGameFlags SpawnAI
 m_eDefaultGameFlags SpawnAI
 m_bIsSavingEnabled 1
}