SCR_MissionHeaderCombatOps {
 World "{92624E92F6AEA8D4}worlds/rknSP02TT.ent"
 m_sName "RKN Time Trials - Everon"
 m_sAuthor "Runekn"
 m_sDescription "Complete time trials across Everon"
 m_sDetails "<Insert scenario details>"
 m_sIcon "{69A58EEE4472AFF5}UI/everon_thumbnail.edds"
 m_sLoadingScreen "{69A58EEE4472AFF5}UI/everon_thumbnail.edds"
 m_sPreviewImage "{69A58EEE4472AFF5}UI/everon_thumbnail.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_bIsSavingEnabled 1
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B55DA84}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B2725C3}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41BE3799A}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B944989}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A40B5073D5}" {
   m_eTypeOfTask DEFEND
  }
 }
}